<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vidul" failures="2" tests="5" name="Test" time="9.183" errors="0" timestamp="2024-09-09T23:59:23 IST">
  <testcase classname="Listener.TestClass" name="Screenshot" time="8.925"/>
  <testcase classname="Listener.TestClass" name="Test1" time="0.006"/>
  <testcase classname="Listener.TestClass" name="Test2" time="0.014">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Listener.TestClass.Test2(TestClass.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="Listener.TestClass" name="Test3" time="0.119">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method Listener.TestClass.Test3() didn&amp;apos;t finish within the time-out 100">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Listener.TestClass.Test3() didn't finish within the time-out 100
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at Listener.TestClass.Test3(TestClass.java:39)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="Listener.TestClass" name="Test4" time="0.001">
    <skipped/>
  </testcase> <!-- Test4 -->
</testsuite> <!-- Test -->
